"""Initial schema.

The baseline revision materialises the declarative metadata directly. This
guarantees the deployed schema is byte-for-byte what the ORM declares, with no
opportunity for a hand-transcribed column to drift. Subsequent revisions are
autogenerated diffs against this baseline in the normal way.
"""

from __future__ import annotations

from alembic import op

from neurotribe.database.base import Base
import neurotribe.database.models  # noqa: F401  (registers all tables)

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
